---
blank_issues_enabled: false
contact_links:
  - name: Boilenest Community Support
    url: https://github.com/devalexanderdaza/boilenest/discussions
    about: Please ask and answer questions here.
